name: Hello world # Just the workflow name (what you see in GitHub UI).

on: workflow_dispatch # Defines when the workflow runs. (manual trigger)
jobs:
  build: # name of the job
    runs-on: ubuntu-latest # a job runs on a runner(VM)
    steps:
      - name: Build step
        run: echo "A demo build"

  test: # name of th job
    runs-on: ubuntu-latest
    steps:
      - name: Test Phase
        run: echo "Runninf Test cases"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Phase
        run: echo "Deploying the app"
  
        
